# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=150, verbose_name='Notice')),
                ('pdf_name', models.CharField(max_length=150, verbose_name='Nom du Fichier PDF')),
                ('found', models.CharField(max_length=150, verbose_name='Disponible')),
                ('last_check', models.CharField(max_length=150, verbose_name='Date de verification')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
            },
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
